export const ASSET_CLASSES: { value: string; label: string }[] = [
  { value: "equity_large_cap", label: "Equity — Large Cap" },
  { value: "equity_mid_cap", label: "Equity — Mid Cap" },
  { value: "equity_small_cap", label: "Equity — Small Cap" },
  { value: "equity_micro_cap", label: "Equity — Micro Cap" },
  { value: "mf_equity", label: "Mutual Fund — Equity" },
  { value: "mf_hybrid", label: "Mutual Fund — Hybrid" },
  { value: "mf_debt", label: "Mutual Fund — Debt" },
  { value: "mf_index", label: "Mutual Fund — Index" },
  { value: "mf_elss", label: "Mutual Fund — ELSS" },
  { value: "gold", label: "Gold" },
  { value: "fd", label: "Fixed Deposit" },
  { value: "ppf", label: "PPF" },
  { value: "epf", label: "EPF" },
  { value: "nps", label: "NPS" },
  { value: "real_estate", label: "Real Estate" },
  { value: "crypto", label: "Crypto" },
  { value: "cash", label: "Cash" },
  { value: "other", label: "Other" },
]
